export const GET_FAVORITE_HOTELS_REQUEST= 'GET_FAVORITE_HOTELS_REQUEST';
export const GET_FAVORITE_HOTELS_SUCCESS= 'GET_FAVORITE_HOTELS_SUCCESS';
export const GET_FAVORITE_HOTELS_FAIL= 'GET_FAVORITE_HOTELS_FAIL';
export const ADD_FAVORITE_HOTEL= 'ADD_FAVORITE_HOTEL';
export const DELETE_FAVORITE_HOTEL= 'DELETE_FAVORITE_HOTEL';


export const POST_FAVORITE_HOTEL_REQUEST= 'POST_FAVORITE_HOTEL_REQUEST';
export const POST_FAVORITE_HOTEL_SUCCESS= 'POST_FAVORITE_HOTEL_SUCCESS';
export const POST_FAVORITE_HOTEL_FAIL= 'POST_FAVORITE_HOTEL_FAIL';

export const DELETE_FAVORITE_HOTEL_REQUEST= 'DELETE_FAVORITE_HOTEL_REQUEST';
export const DELETE_FAVORITE_HOTEL_SUCCESS= 'DELETE_FAVORITE_HOTEL_SUCCESS';
export const DELETE_FAVORITE_HOTEL_FAIL= 'DELETE_FAVORITE_HOTEL_FAIL';
