export const HOTEL_CREATE_REQUEST= 'HOTEL_CREATE_REQUEST';
export const HOTEL_CREATE_SUCCESS= 'HOTEL_CREATE_SUCCESS';
export const HOTEL_CREATE_FAIL= 'HOTEL_CREATE_FAIL';  
export const HOTEL_CREATE_RESET= 'HOTEL_CREATE_RESET';  